#!/bin/sh -
#
# Copyright (c) 2015  Oliver Pinter <oliver.pinter@hardenedbsd.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# PROVIDE: secadm
# REQUIRE: ldconfig
# BEFORE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name="secadm"
rcvar="secadm_enable"
start_precmd="secadm_prestart"
stop_cmd="secadm_stop"

load_rc_config $name
: ${secadm_enable:="NO"}
: ${secadm_rules:="/usr/local/etc/secadm.rules"}

command="/usr/sbin/secadm"
command_args="load ${secadm_rules}"

secadm_prestart()
{
	if [ ! -f ${secadm_rules} ]
	then
		echo "missing rules file: ${secadm_rules}"
		return 1
	fi

	if ! /sbin/kldstat -qm secadm; then
		/sbin/kldload secadm
	fi
}

secadm_stop()
{
	${command} flush
}

if [ ! -x ${command} ]
then
    command="/usr/local/sbin/secadm"
fi

run_rc_command "$1"
